### ISSUE TITLE
how do i render static js file with this structure ?

### ISSUE THREAD

**Issue by AbhiAdr** [corylanou/tns-restful-json-api#14]
i added route under routes like this 

Route{
		"Js",
		"GET",
		"/js",
		Js,
	},
 
and under my main package i have a function like this 

func Js(w http.ResponseWriter, r *http.Request) {
	fmt.Println("boom!!!")
	http.StripPrefix("/js/", http.FileServer(http.Dir("public/js/")))
}

and when i try to access my bundel.js like this it shows 404

http://localhost:8086/js/bundle.js

**Comment by AbhiAdr** [comment]
hi i really appreciate for the article , it help me a lot but can you help me to solve this ?

**Comment by AbhiAdr** [comment]
i did it with 
	s := http.StripPrefix("/js/", http.FileServer(http.Dir("./public/")))
	router.PathPrefix("/js/").Handler(s)

in main func

**Comment by a-hilaly** [comment]
https://github.com/gorilla/mux#static-files
hope this can help you

**Comment by corylanou** [comment]
Sorry I didn't get to this. I'm hoping you found your answer by now.  Closing this issue for now.
