### ISSUE TITLE
How to organize a similar controllerr directory？

### ISSUE THREAD

**Issue by yumin5723** [corylanou/tns-restful-json-api#18]
hi,i'm glad to see your ariticle,i'm a new student,in the actual project,has user api,goods api...,we can not write all codes in hanlers.go,how can i organize directory?how can i  let code run?

**Comment by corylanou** [comment]
It's not uncommon to have a `handlers` package (directory), and keep your files in there. So you would have a file for each model, etc.  There are plenty of other ways to organize packages as well.  

There are a lot of opinions on this, and mileage will vary.  My best advice is to simply write the code, and re-factor as needed.  But don't let organization get in the way of progress.

FWIW, here is a thread on the topic. https://www.reddit.com/r/golang/comments/6t0anl/go_newbie_how_to_organize_code/
