### ISSUE TITLE
Same issue for me ./main.go:10: undefined: NewRouter

### ISSUE THREAD

**Issue by mgiardinelli** [corylanou/tns-restful-json-api#3]

**Comment by cdrage** [comment]
@mgiardinelli 

The original author needs to clarify this for new users.

But in order to run this example. Simple do:

``` bash
go build
```

If you do

``` bash
ls
```

You'll see a binary file. Just run it (it created api for me), so just run:

``` bash
./api
```

and look at localhost:8080

**Comment by corylanou** [comment]
Fixed in #4
